### ISSUE TITLE
MCP svelte-mcp fails to start on Windows 11 when Zed is used with WSL2 (wrong node path / env)

### ISSUE THREAD

**Issue by GregFedy** [ghostdevv/zed-svelte-mcp#1]
On Windows 11 with WSL2 configured in Zed, the Svelte MCP Server fails to start. Zed tries to spawn its bundled Node inside the Windows environment and the server never comes up, even after reinstalling the extension.

From the MCP Servers settings panel:

> failed to spawn command
> "C:\\Users\\<user>\\AppData\\Local\\Zed\\node\\node-v24.11.0-win-x64\\node.exe"
> "C:\\Users\\<user>\\AppData\\Local\\Zed\\extensions\\work\\svelte-mcp\\node_modules\\@sveltejs\\mcp\\dist\\index.js"

I am working on projects that live in WSL2 (Ubuntu-24.04), but Zed itself is running as a Windows application.

**Comment by ghostdevv** [comment]
Hey @GregFedy, I actually think this was caused by the svelte mcp package changing it's entry point file name. I fixed that in this extension earlier this week, can you confirm whether or not this is working for you?

**Comment by GregFedy** [comment]
> Hey [@GregFedy](https://github.com/GregFedy), I actually think this was caused by the svelte mcp package changing it's entry point file name. I fixed that in this extension earlier this week, can you confirm whether or not this is working for you?

<img width="1912" height="1077" alt="Image" src="https://github.com/user-attachments/assets/690115a4-6522-4eb2-a34d-09d4e2df1488" />

Still not working :(

**Comment by ghostdevv** [comment]
Curious, are there any more logs under the `zed: open log` command?

<img width="555" height="199" alt="Image" src="https://github.com/user-attachments/assets/8eff772f-f8c2-439d-8296-cf560287d9bc" />

**Comment by SHJordan** [comment]
> zed: open log

<details><summary>Details</summary>
<p>

```log
2026-01-15T23:43:18-03:00 INFO  [extension_host] installing extension svelte latest version
2026-01-15T23:43:19-03:00 INFO  [extension_host] rebuilt extension index in 9.8489ms
2026-01-15T23:43:19-03:00 INFO  [extension_host] extensions updated. loading 1, reloading 0, unloading 0
2026-01-15T23:43:19-03:00 INFO  [extension_host::headless_host] (remote server) failed to load extension: svelte, No extension manifest found for extension svelte
2026-01-15T23:43:19-03:00 INFO  [extension_host] Uploading extension svelte to RemotePathBuf { style: Posix, string: "/home/shjordan/.local/share/zed/remote_extensions/uploads/svelte" }
2026-01-15T23:43:19-03:00 INFO  [extension_host] Finished uploading extension svelte
2026-01-15T23:43:20-03:00 INFO  [extension_host::headless_host] (remote server) Loaded language server: svelte-language-server
2026-01-15T23:43:43-03:00 INFO  [extension_host] installing extension svelte-mcp latest version
2026-01-15T23:43:44-03:00 INFO  [extension_host] rebuilt extension index in 9.4594ms
2026-01-15T23:43:44-03:00 INFO  [extension_host] extensions updated. loading 1, reloading 0, unloading 0
2026-01-15T23:43:44-03:00 INFO  [extension_host] rebuilt extension index in 10.4072ms
2026-01-15T23:43:44-03:00 INFO  [extension_host] extensions updated. loading 0, reloading 1, unloading 0
2026-01-15T23:43:52-03:00 ERROR [project::context_server_store] svelte-mcp context server failed to start: failed to spawn command "C:\\Program Files\\PowerShell\\7\\pwsh.exe" "-C" "C:\\Users\\shjor\\AppData\\Local\\Zed\\node\\node-v24.11.0-win-x64\\node.exe \'C:/Users/shjor/AppData/Local/Zed/extensions/work/svelte-mcp/node_modules/@sveltejs/mcp/dist/index.mjs\'")
2026-01-15T23:43:57-03:00 INFO  [assistant_text_thread::text_thread_store] registering context server command: "svelte-task"
2026-01-15T23:43:57-03:00 INFO  [assistant_text_thread::text_thread_store] registering context server command: "svelte-task"
2026-01-15T23:44:39-03:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce RTX 3070", driver_name: "NVIDIA Corporation", driver_info: "591.74 r591_66" }
2026-01-15T23:44:39-03:00 INFO  [gpui::platform::windows::directx_renderer] Updating subpixel_sprite_pipeline buffer size from 512 to 8192
2026-01-15T23:44:40-03:00 INFO  [context_server] Using HTTP transport for https://mcp.context7.com/mcp
2026-01-15T23:44:41-03:00 INFO  [assistant_text_thread::text_thread_store] registering context server command: "svelte-task"
2026-01-15T23:44:41-03:00 INFO  [assistant_text_thread::text_thread_store] registering context server command: "svelte-task"
2026-01-15T23:44:51-03:00 ERROR [crates/project/src/context_server_store.rs:378] Failed to get context server settings
2026-01-15T23:44:51-03:00 INFO  [project::lsp_store] stopping language server json-language-server
2026-01-15T23:44:51-03:00 INFO  [lsp] starting language server process. binary path: "C:\\Users\\shjor\\AppData\\Local\\Zed\\node\\node-v24.11.0-win-x64\\node.exe", working directory: "C:\\Users\\shjor\\AppData\\Roaming\\Zed", args: ["C:\\Users\\shjor\\AppData\\Local\\Zed\\languages\\json-language-server\\node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2026-01-15T23:44:52-03:00 ERROR [codestral] Codestral: Failed to fetch completion: Codestral API error: 404 Not Found - {"detail":"Not Found"}
2026-01-15T23:45:16-03:00 INFO  [gpui::platform::windows::directx_renderer] Updating underline_pipeline buffer size from 4 to 16
2026-01-15T23:45:16-03:00 INFO  [gpui::platform::windows::directx_renderer] Updating underline_pipeline buffer size from 16 to 64
2026-01-15T23:45:16-03:00 INFO  [gpui::platform::windows::directx_renderer] Updating quad_pipeline buffer size from 64 to 128
2026-01-15T23:45:16-03:00 INFO  [gpui::platform::windows::directx_renderer] Updating underline_pipeline buffer size from 64 to 128
2026-01-15T23:45:16-03:00 INFO  [gpui::platform::windows::directx_renderer] Updating quad_pipeline buffer size from 128 to 256
2026-01-15T23:45:16-03:00 INFO  [gpui::platform::windows::directx_renderer] Updating underline_pipeline buffer size from 128 to 256
2026-01-15T23:45:17-03:00 INFO  [gpui::platform::windows::directx_renderer] Updating quad_pipeline buffer size from 256 to 512
2026-01-15T23:45:17-03:00 INFO  [gpui::platform::windows::directx_renderer] Updating underline_pipeline buffer size from 256 to 512
```


</p>
</details> 

This should suffice. Also having the same issue.

**Comment by ghostdevv** [comment]
@maxbrunsfeld apologies for the tag, but I'm wondering if you know off the top of your head what causes this? I saw you fixed it in https://github.com/akbxr/zed-mcp-server-context7/issues/1 but as far as I can tell our setup is functionally equivalent? If you don't know then no worries, I'll get a windows VM to debug.
